language: python

python:
  - "3.6"

before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/conda
  - export PATH="$HOME/conda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -n test_env python=$TRAVIS_PYTHON_VERSION pip cmake
  - source activate test_env

install:
  - conda install -q -c rdkit rdkit
  - conda install -q flake8
  - python setup.py install

script:
  - flake8 moses/metrics/
  - flake8 setup.py
  - flake8 scripts/
  - flake8 moses/*.py
  - python tests/test_metrics.py
