name: text_gen
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - babel=2.5.3=py36_0
  - cymem=1.31.2=py36_0
  - cytoolz=0.8.2=py36_0
  - dill=0.2.7.1=py36_0
  - imagesize=1.0.0=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipywidgets=7.2.1=py36_0
  - jupyter_client=5.2.3=py36_0
  - keras=2.1.5=py36_0
  - lazy=1.3=py36_0
  - libgpuarray=0.7.6=0
  - mako=1.0.7=py36_0
  - msgpack-numpy=0.4.1=py_0
  - msgpack-python=0.4.8=py36_0
  - murmurhash=0.28.0=py36_0
  - notebook=5.4.1=py36_0
  - numpydoc=0.8.0=py36_0
  - olefile=0.45.1=py36_0
  - pexpect=4.5.0=py36_0
  - pip=9.0.3=py36_0
  - plac=0.9.6=py36_0
  - preshed=1.0.0=py36_0
  - pygpu=0.7.6=py36_0
  - regex=2017.11.09=py36_0
  - setuptools=39.0.1=py36_0
  - spacy=2.0.11=py36_0
  - termcolor=1.1.0=py36_1
  - theano=1.0.1=py36_1
  - thinc=6.10.2=py36_0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py36_0
  - typing=3.6.4=py36_0
  - ujson=1.35=py36_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - wrapt=1.10.11=py36_0
  - alabaster=0.7.10=py36h306e16b_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36h0f667ec_1
  - cryptography=2.2.2=py36h14c3975_0
  - cudatoolkit=9.0=h13b8566_0
  - cycler=0.10.0=py36h93f1223_0
  - cython=0.28.2=py36h14c3975_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - docutils=0.14=py36hb0f60f5_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - ftfy=4.4.3=py36_0
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.7.1=py36h3585f63_0
  - hdf5=1.10.1=h9caa474_1
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py36h82fb2a8_1
  - intel-openmp=2018.0.0=8
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36ha16c418_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter=1.0.0=py36_4
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - kiwisolver=1.0.1=py36h764f252_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=hf84eae3_0
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.2.2=py36h0e671d2_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - ncurses=6.0=h9df7e31_2
  - ninja=1.8.2=h6bb024c_1
  - nltk=3.2.5=py36h7532b22_0
  - numpy=1.12.1=py36he24570b_1
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py36_0
  - pandas=0.22.0=py36hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.2.0=py36_0
  - pcre=8.42=h439df22_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pillow=5.1.0=py36h3deb7b8_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - protobuf=3.5.2=py36hf484d3e_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36hf9f622e_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=17.5.0=py36h20ba746_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.9.2=py36h751905a_0
  - pysocks=1.6.8=py36_0
  - python=3.6.5=hc3d631a_1
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - pyyaml=3.12=py36hafb9ca4_1
  - pyzmq=17.0.0=py36h14c3975_0
  - qt=5.9.5=h7e424d6_0
  - qtconsole=4.3.1=py36h8f73b5b_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py36he2e5f8d_1
  - scikit-learn=0.19.1=py36h7aa7ec6_0
  - scipy=1.0.1=py36hfc37229_0
  - send2trash=1.5.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36h372c433_1
  - snowballstemmer=1.2.1=py36h6febd40_0
  - sphinx=1.7.3=py36_0
  - sphinxcontrib=1.0=py36h6d0f590_1
  - sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
  - sqlite=3.23.1=he433501_0
  - tensorflow=1.1.0=np112py36_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.7=hc745277_3
  - tqdm=4.23.0=py36_0
  - traitlets=4.3.2=py36h674d592_0
  - urllib3=1.22=py36hbe7ace6_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - werkzeug=0.14.1=py36_0
  - xz=5.2.3=h5e939de_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - cuda90=1.0=h6433d27_0
  - pytorch=0.4.0=py36_cuda9.0.176_cudnn7.1.2_1
  - torchvision=0.2.1=py36_1
  - pip:
    - en-core-web-sm==2.0.0
    - gist==0.0.8
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.4
    - jupyter-nbextensions-configurator==0.4.0
    - lxml==4.2.1
    - pathlib==1.0.1
    - pytorch-nlp==0.2.0
    - revtok==0.0.2
    - torch==0.4.0
    - torchtext==0.3.0
prefix: /home/stasbel/miniconda3/envs/text_gen
