name: LatentGAN
channels:
  - rdkit
  - pytorch
  - openeye
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.5.15=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py36_0
  - cffi=1.11.5=py36he75722e_1
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.6.0=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - git=2.20.1=pl526hacde149_0
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.11=py_0
  - glib=2.56.2=hd408876_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - krb5=1.16.1=h173b8e3_7
  - libboost=1.65.1=habcd387_4
  - libcurl=7.64.0=h20c2e04_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libssh2=1.8.1=h22169c7_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=3.0.1=py36_0
  - matplotlib=3.0.2=py36h5429711_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - more-itertools=6.0.0=py36_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - nose=1.3.7=py36_2
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openeye-toolkits=2018.10.1=py36_0
  - openssl=1.1.1c=h7b6447c_1
  - pandas=0.24.1=py36he6710b0_0
  - pcre=8.42=h439df22_0
  - perl=5.26.2=h14c3975_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.1=py36_0
  - pixman=0.36.0=h7b6447c_0
  - pluggy=0.9.0=py36_0
  - protobuf=3.6.1=py36he6710b0_0
  - py=1.8.0=py36_0
  - py-boost=1.65.1=py36hf484d3e_4
  - pycparser=2.19=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - pytest=4.3.1=py36_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.7.5=py36_0
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - pytz=2018.9=py36_0
  - qt=5.9.7=h5867ecd_1
  - rdkit=2018.09.1.0=py36h71b666b_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - smmap2=2.0.5=py_0
  - sqlite=3.26.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he68c306_0
  - tensorflow-base=1.12.0=gpu_py36h8e0ae2d_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - tqdm=4.31.1=py_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - chardet==3.0.4
    - decorator==4.3.2
    - deepsmiles==1.0.1
    - fcd==1.0
    - fcd-torch==1.0.7
    - gpy==1.9.6
    - gpyopt==1.2.5
    - guacamol==0.5.0
    - idna==2.8
    - imageio==2.5.0
    - imageio-ffmpeg==0.2.0
    - joblib==0.13.2
    - keras==2.2.4
    - molsets==0.1.2
    - moviepy==1.0.0
    - paramz==0.9.4
    - proglog==0.1.9
    - py4j==0.10.7
    - pyspark==2.4.1
    - pyyaml==5.1
    - requests==2.21.0
    - seaborn==0.9.0
    - tensorboardx==1.6
    - torch==1.0.1.post2
    - torchsummary==1.5.1
    - torchvision==0.2.1
    - urllib3==1.24.1

